/*
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } = require('fs');
const tar = require('tar');
const path = require('path');

function ensureDirSync(path) {
  !existsSync(path) && mkdirSync(path, { recursive: true });
}

function removeSync(path) {
  rmSync(path, { recursive: true, force: true });
}

const HEADER = `/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable quotes */
// file generated by ./scripts/updateRuntimeDependencies.js
`;

/**
 * Packages the TypeScriptRuntime.ts and the contents of the 'drafting'
 * directory as this code is used by generated code and must be copied to
 * the output folder when we generate typescript code for a template.
 *
 * This script requires a sibling template-engine checkout. If not present,
 * it skips regeneration and uses the existing committed runtime.ts file.
 */
const templateEnginePath = '../template-engine/src/drafting';

if (!existsSync(templateEnginePath)) {
  console.log('Sibling template-engine not found, using existing runtime.ts');
  process.exit(0);
}

ensureDirSync('dist');

tar
  .c(
    {
      gzip: true,
      file: path.join('dist', 'runtime.tgz'),
    },
    ['../template-engine/src/drafting', '../template-engine/src/TypeScriptRuntime.ts']
  )
  .then((_) => {
    const runtime = readFileSync(path.join('dist', 'runtime.tgz')).toString(
      'base64'
    );

    writeFileSync(
      './src/runtime/runtime.ts',
      `
${HEADER}

export const RUNTIME_TGZ_BASE64 = '${runtime}';
`
    );
  });
